### ISSUE TITLE
Imposible to autorise after registration

### ISSUE THREAD

**Issue by nik9str** [nc-student-group/phone-company#103] opened 2017-05-27 13:28 UTC
Registration on nik9str@gmail.com
Password: rootroot+
After changing password autorisation became possible
http://joxi.ru/J2bx3Y9i44babr

**Comment by serhiizem** [comment] 2017-05-27 17:35
Possible duplicate of https://github.com/nc-student-group/phone-company/issues/107

**Comment by serhiizem** [comment] 2017-05-28 16:23
Issue was not related to the code. Closed

**Comment by serhiizem** [comment] 2017-05-29 14:11
Problem unsolved as it is related to ShaPasswordEncoder implementation. The only solution is not to include "+" in password.

**Closed as completed** 2017-05-29 14:12 UTC
Labels: duplicate, bug
